.travis.yml
README.md

This PR tries to address: [OP-123](https://openhospital.atlassian.net/browse/OP-123) and [OP-122](https://openhospital.atlassian.net/browse/OP-122)  
Test build: https://travis-ci.org/pviotti/openhospital-api/builds/594216356
Some things are work-in-progress and will be addressed in future PRs. For instance:
- it uses a specific branch of openhospital-core instead of master
- tests are skipped because they'd require Docker

Add README.md and Travis configuration

---

pom.xml

Found out that running tests shows warnings about [SLF4J](https://www.baeldung.com/slf4j-classpath-multiple-bindings) bindings. Altough it's just a warning, we could introduce the following exclusions in pom.xml? (it was partially done)
```
<exclusions>
<exclusion>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-tomcat</artifactId>
</exclusion>
<exclusion>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-logging</artifactId>
</exclusion>
</exclusions>
```
...
```
<dependency>
<groupId>org.isf</groupId>
<artifactId>OH-core</artifactId>
<version>1.9</version>
<exclusions>
<exclusion>
<groupId>org.hibernate.javax.persistence</groupId>
<artifactId>hibernate-jpa-2.0-api</artifactId>
</exclusion>
<exclusion>
<groupId>org.slf4j</groupId> …
```

Resolving SFL4J multiple bindings

---

src/main/java/org/isf/accounting/dto/BillDTO.java

Updating setter and getter on `BillDTO` class for `PatientDTO patient` field to avoid conflict with `setPatient(boolean)` method.
>  org.isf.accounting.dto.BillDTO["patient"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of boolean out of START_OBJECT token 
```
@@ -159,11 +159,11 @@ public class BillDTO {
this.listId = listId;
}
-       public PatientDTO getPatient() {
+       public PatientDTO getPatientDTO() {
return patient;
}
-       public void setPatient(PatientDTO patient) {
+       public void setPatientDTO(PatientDTO patient) {
this.patient = patient;
}
```

Fixing OP-204 com.fasterxml.jackson.databind.JsonMappingException

---

src/main/java/org/isf/accounting/rest/BillController.java
src/test/java/org/isf/accounting/data/BillDTOHelper.java
src/test/java/org/isf/accounting/data/BillHelper.java
src/test/java/org/isf/accounting/data/BillItemsDTOHelper.java
src/test/java/org/isf/accounting/data/BillPaymentsDTOHelper.java
src/test/java/org/isf/accounting/data/FullBillDTOHelper.java
src/test/java/org/isf/accounting/rest/BillControllerTest.java
src/test/java/org/isf/testing/rest/ControllerBaseTest.java

`BillControllerTest` and Helper classes have been updated to fit new pattern.
Note: 8 To do tasks are annotated on BillController and `BillControllerTest` in order to fix easily all problems and tests failing because naming problems exposed on OP-205.

OP-196 Adding BillControllerTest after New Pattern

---

src/main/java/org/isf/accounting/rest/BillController.java
src/main/java/org/isf/admission/rest/AdmissionController.java
src/main/java/org/isf/admtype/rest/AdmissionTypeController.java
src/main/java/org/isf/agetype/rest/AgeTypeController.java
src/main/java/org/isf/disctype/rest/DischargeTypeController.java
src/main/java/org/isf/dlvrrestype/rest/DeliveryResultTypeController.java
src/main/java/org/isf/dlvrtype/rest/DeliveryTypeController.java
src/main/java/org/isf/exatype/rest/ExamTypeController.java
src/main/java/org/isf/malnutrition/rest/MalnutritionController.java
src/main/java/org/isf/medical/rest/MedicalController.java
src/main/java/org/isf/medicalstockward/rest/MedicalStockWardController.java
src/main/java/org/isf/medstockmovtype/rest/MedStockMovementTypeController.java
src/main/java/org/isf/medtype/rest/MedicalTypeController.java
src/main/java/org/isf/menu/rest/UserController.java
src/main/java/org/isf/opd/rest/OpdController.java
src/main/java/org/isf/operation/rest/OperationController.java
src/main/java/org/isf/opetype/rest/OperationTypeController.java
src/main/java/org/isf/patient/rest/PatientController.java
src/main/java/org/isf/patvac/rest/PatVacController.java
src/main/java/org/isf/pregtreattype/rest/PregnantTreatmentTypeController.java
src/main/java/org/isf/priceslist/rest/PriceListController.java
src/main/java/org/isf/pricesothers/rest/PricesOthersController.java
src/main/java/org/isf/sms/rest/SmsController.java
src/main/java/org/isf/supplier/rest/SupplierController.java
src/main/java/org/isf/therapy/rest/TherapyController.java
src/main/java/org/isf/vaccine/rest/VaccineController.java
src/main/java/org/isf/vactype/rest/VaccineTypeController.java
src/main/java/org/isf/visits/rest/VisitsController.java
src/main/java/org/isf/ward/rest/WardController.java

Change non-constant string concatenations used as arguments to SLF4J methods. Non-constant concatenations will be evaluated at runtime even when the logging message is not logged; this can negatively impact performance.  A parameterized log message will not be evaluated when logging is disabled.
Also replaced a `System.out.println` call with a logging call instead.

Chore: use a parameterized log message

---

src/test/java/org/isf/admtype/rest/AdmissionTypeControllerTest.java
src/test/java/org/isf/disctype/rest/DischargeTypeControllerTest.java

The array `admtFounds` is created and stored into but never used.  Remove the code and the tests pass.

Chore - remove useless object creation/store

---

src/main/java/org/isf/admission/rest/AdmissionController.java
src/main/java/org/isf/admtype/rest/AdmissionTypeController.java
src/main/java/org/isf/disctype/rest/DischargeTypeController.java
src/main/java/org/isf/dlvrrestype/rest/DeliveryResultTypeController.java
src/main/java/org/isf/dlvrtype/rest/DeliveryTypeController.java
src/main/java/org/isf/opd/rest/OpdController.java
src/main/java/org/isf/patvac/rest/PatVacController.java
src/main/java/org/isf/pregtreattype/rest/PregnantTreatmentTypeController.java
src/main/java/org/isf/priceslist/rest/PriceListController.java
src/main/java/org/isf/pricesothers/rest/PricesOthersController.java

Casting `ResponseEntity.ok()` to `ResponseEntity<Boolean>` is redundant.

Chore - remove redundant cast

---

src/main/java/org/isf/accounting/rest/BillController.java
src/main/java/org/isf/vaccine/rest/VaccineController.java
src/main/java/org/isf/vactype/rest/VaccineTypeController.java
src/main/java/org/isf/visits/dto/VisitDTO.java

The method itself takes care of the conversion to a String object.
BTW, in the last case:
```
@Override
public String toString() {
return "VisitDTO{" +
", patient=" + patient +
", date=" + date +
", note='" + note + '\'' +
", sms=" + sms +
```
the `patient` `toString()` method is not overridden so it will just object an object id.

Chore - remove unnecessary toString()

---

src/main/java/org/isf/shared/Mapper.java

`Public` modifier are not used/needed in Interface definitions.

Chore Public modifiers not used in Interfaces

---

src/main/java/org/isf/medicalstock/rest/StockMovementController.java
src/main/java/org/isf/medicalstockward/rest/MedicalStockWardController.java
src/main/java/org/isf/menu/rest/UserController.java

When calling a method in a loop (e.g. `collection.add(x)`) it can  be replaced with calling a bulk method (e.g. `collection.addAll(listOfX)`.

Chore Use bulk method instead of loop

---

src/main/java/org/isf/lab/rest/LaboratoryController.java

Found using SpotBugs (the successor to FindBugs).
The description of the issue:
````
Suspicious reference comparison
This method compares two reference values using the == or != operator, where the correct way to compare instances of this 
type is generally with the equals() method. It is possible to create distinct instances that are equal but do not 
compare as == since they are different objects. Examples of classes which should generally not be compared by
reference are java.lang.Integer, java.lang.Float, etc.
````
So I changed the `==` or `!=` into the corresponding version using `equals()`.
FYI @emecas

Chore Fix reference comparison

---

src/main/java/org/isf/accounting/rest/BillController.java

Found using SpotBugs (successor to FindBugs).
The issue that was found:
````
Nullcheck of value previously dereferenced 
A value is checked here to see whether it is null, but this value can't be null because it was previously dereferenced 
and if it were null a null pointer exception would have occurred at the earlier dereference. Essentially, this code 
and the previous dereference disagree as to whether this value is allowed to be null. Either the check is 
redundant or the previous dereference is erroneous.
````
Changes:
The logging of `newBillDto` at the start of the method if it was null would be a NPE.   Added a null check before the logging, removed the `toString()` in the logger call as the log method handles that, and then removed the null check near the end of the method just …

Chore Fix possible null dereference

---

src/test/java/org/isf/agetype/rest/AgeTypeControllerTest.java
src/test/java/org/isf/disease/rest/DiseaseControllerTest.java
src/test/java/org/isf/distype/rest/DiseaseTypeControllerTest.java
src/test/java/org/isf/dlvrrestype/rest/DeliveryResultTypeControllerTest.java
src/test/java/org/isf/dlvrtype/rest/DeliveryTypeControllerTest.java
src/test/java/org/isf/vaccine/rest/VaccineControllerTest.java
src/test/java/org/isf/vactype/rest/VaccineTypeControllerTest.java
src/test/java/org/isf/visits/rest/VisitsControllerTest.java
src/test/java/org/isf/ward/rest/WardControllerTest.java

With method signature: `throws JsonProcessingException, Exception` there is no need for the `JsonProcessingException` given the more general `Exception`.

Chore Only need general Exception defined

---

src/main/java/org/isf/dlvrtype/rest/DeliveryTypeController.java
src/main/java/org/isf/exam/rest/ExamController.java
src/main/java/org/isf/security/LoginApi.java
src/main/java/org/isf/stats/rest/ReportsController.java
src/main/java/org/isf/vaccine/rest/VaccineController.java
src/test/java/org/isf/dlvrtype/rest/DeliveryTypeControllerTest.java
src/test/java/org/isf/vaccine/rest/VaccineControllerTest.java

https://openhospital.atlassian.net/browse/OP-376
Due to some mistakes mainly on SpringFox annotations and REST controllers paths definitions, the autogenerated api-docs has some errors against the Swagger 2 specification.To check that, I copy the generated api-docs (from /oh-api/v2/api-docs) and paste it in swagger editor. Those are the reported errors:

OP-376 Swagger 2 generated spec compliance fixes 

---

src/main/java/org/isf/admission/rest/AdmissionController.java

The method `admissionManager.newAdmissionReturnKey(newAdmission)` returns an `int` and not an `Integer` thus making the test for null and `aId.intValue()` unnecessary.
`Unboxing`,  that is the explicit unwrapping of wrapped primitive values,  is unnecessary under Java 5 and newer, and can be safely removed.
Found with IntelliJ Analyze plugin.

Chore: unnecessary unboxing

---

pom.xml

We aren't ready to move to spring boot 2.x train yet but at least we can move to the latest 1.x version in the meantime.

Bump spring-boot-starter-parent from 1.4.0.RELEASE to 1.5.22.RELEASE

---

src/main/java/org/isf/agetype/rest/AgeTypeController.java

This was the only occurrence in the code where the `body` value was a variable and not `null` when there was no content.   It doesn't change the code but makes it consistent.
This was found with Spotbugs where it complained about loading a known null value.

Chore: consistency

---

src/main/java/org/isf/menu/rest/UserController.java

Use `noneMatch()` instead of negating `anyMatch()` which might be overlooked in a quick read.
Found with IntelliJ Analyze plugin.

Chore: use noneMatch() instead of negation

---

pom.xml
src/main/java/org/isf/ward/dto/WardDTO.java

Combine the recent dependabot updates and fix the failing test that was caused by the addition of a new field (visitDuration) to the Ward object.
In addition resolved the multiple logger issues when running the unit tests:
<pre>
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/dbm/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.17.2/log4j-slf4j-impl-2.17.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/dbm/.m2/repository/org/slf4j/slf4j-reload4j/1.7.36/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
</pre>

Chore: updates for dependabot updates

---

pom.xml

Combine recent updates for `jackson-modules-java8` (to match core update) and `java-jwt`.   For `java-jwt` did not go all the way to version 4.4.0 but rather stayed at 3.19.4 because the CHANGELOG indicated breaking changes.   Someone who understands the use of `jwt` in this project needs to review [the Migration Guide](https://github.com/auth0/java-jwt/blob/master/MIGRATION_GUIDE.md) before moving to 4.X.X.
Ran `mvn clean test` successfully.

Chore: combine two recent dependabot updates for testing

---

src/main/java/org/isf/login/dto/LoginResponse.java
src/main/java/org/isf/shared/pagination/PageInfoDTO.java

The class doesn't extend any base class so there is no `super()`.

Chore: remove unnecessary call to `super()`

---

src/main/java/org/isf/medicalstock/rest/StockMovementController.java
src/main/java/org/isf/menu/rest/UserController.java
src/test/java/org/isf/accounting/rest/BillControllerTest.java

Use a single call to a parameterized constructor which simplifies the code.   For some collection types the replacement is more performant.

Chore: single call instead of new() followed by addAll()

---

src/main/java/org/isf/patient/rest/PatientController.java

Interestingly it had been a single character for a long time until some mass mergers were undertaken.  Using a single character is usually more performant.

Chore: use char when String is a single character

---

src/main/java/org/isf/admtype/rest/AdmissionTypeController.java
src/test/java/org/isf/admtype/rest/AdmissionTypeControllerTest.java

See [OP-1130](https://openhospital.atlassian.net/browse/OP-1130)
Changes for the admtype package.
Matching changes for CORE PR: https://github.com/informatici/openhospital-core/pull/1105
[OP-1130]: https://openhospital.atlassian.net/browse/OP-1130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-1130 improve JPA methods - admtype package

---

src/test/java/org/isf/vactype/rest/VaccineTypeControllerTest.java

See OP-1130
When incorporating the recent changes one of the test files in `vactype` failed to compile; this fixes the issue.
I don't understand how this wasn't caught sooner.

OP-1130 improve JPA methods - vactype package fix

---

src/test/java/org/isf/OpenHospitalApiApplicationTests.java
src/test/java/org/isf/lab/rest/LaboratoryControllerTest.java

See OP-336.
Not sure if to have contextLoads() test though, by the moment it is slows down the whole test suite

OP-336 Convert test to junit5 and test contextLoads() method

---

.github/workflows/maven.yml
.github/workflows/openapi.yml

This is an alternative solution to #421 in order to separate the `build` (may success) and `openapi` generation (may fail).

Separate openapi check workflow from build one
