pom.xml, src/main/resources/application.properties
https://openhospital.atlassian.net/browse/OP-178
=> OP-178 #comment fix spring version conflict between core #time 4h

src/main/java/org/isf/patient/rest/PatientController.java, src/test/java/org/isf/patient/rest/PatientControllerTest.java
Fix patient tests on new proposal pattern
=> OP-6 Fix patient tests on new proposal pattern

src/main/java/org/isf/admtype/rest/AdmissionTypeController.java, src/test/java/org/isf/admtype/data/AdmissionTypeDTOHelper.java, src/test/java/org/isf/admtype/rest/AdmissionTypeControllerTest.java
Related to OP-196 task
- AdmissionTypeDTOHelper 
- AdmissionTypeControllerTest
=> Adding  AdmissionTypeController Test

src/main/java/org/isf/agetype/rest/AgeTypeController.java, src/test/java/org/isf/agetype/data/AgeTypeHelper.java, src/test/java/org/isf/agetype/rest/AgeTypeControllerTest.java
Related to OP-196 task
- Updating constructor for `AgeTypeController`
- Adding `AgeTypeControllerTest` and `AgeTypeHelper`
=> OP-196 | Adding AgeTypeController Test 

src/main/java/org/isf/disctype/rest/DischargeTypeController.java, src/test/java/org/isf/disctype/data/DischargeTypeHelper.java, src/test/java/org/isf/disctype/rest/DischargeTypeControllerTest.java
Related to OP-196 task
DischargeTypeHelper
DischargeTypeTest
=> OP196 | Adding DischargeType Test

src/main/java/org/isf/accounting/rest/BillController.java, src/test/java/org/isf/accounting/rest/BillControllerTest.java
This new PR is applying all adjustments in pending for all the failing tests on `BillControllerTest` related to OP-205 bug, after the adoption of the new patter.  
Related to:
https://github.com/informatici/openhospital-gui/pull/96
https://github.com/informatici/openhospital-core/pull/85
=> Fixing OP-205 for API (GUI PR#96 and CORE PR#85)

src/main/java/org/isf/admission/rest/AdmissionController.java, src/main/java/org/isf/disease/rest/DiseaseController.java, src/test/java/org/isf/admission/data/AdmissionHelper.java, src/test/java/org/isf/admission/rest/AdmissionControllerTest.java, src/test/java/org/isf/admtype/data/AdmissionTypeDTOHelper.java, src/test/java/org/isf/disctype/data/DischargeTypeHelper.java, src/test/java/org/isf/disease/data/DiseaseHelper.java, src/test/java/org/isf/disease/rest/DiseaseControllerTest.java, src/test/java/org/isf/operation/data/OperationHelper.java, src/test/java/org/isf/patient/data/PatientHelper.java, src/test/java/org/isf/patient/rest/PatientControllerTest.java, src/test/java/org/isf/pregtreattype/data/PregnantTreatmentTypeHelper.java, src/test/java/org/isf/ward/data/WardHelper.java
-     Add Disease helper
-     Pass 13 tests DiseaseControllerTest
=> OP-196 | Adding Disease Controller Test 

pom.xml
[ERROR] Failed to execute goal on project openhospital-api: Could not resolve dependencies for project org.isf:openhospital-api:jar:0.0.1: Could not find artifact commons-logging:commons-logging:jar:1.2.1-SNAPSHOT ->
=> [OP-238] Fixing Compilation Issue 

src/main/java/org/isf/dlvrrestype/rest/DeliveryResultTypeController.java, src/test/java/org/isf/dlvrrestype/data/DeliveryResultTypeHelper.java, src/test/java/org/isf/dlvrrestype/rest/DeliveryResultTypeControllerTest.java
- Added and passed 4 tests `DeliveryResultTypeControllerTest`
- Added `DeliveryResultTypeHelper`
- Updated `DeliveryResultTypeController`
=> OP-196 | Adding Delivery Result Type Controller Test

src/main/java/org/isf/dlvrtype/rest/DeliveryTypeController.java, src/test/java/org/isf/dlvrtype/data/DeliveryTypeHelper.java, src/test/java/org/isf/dlvrtype/rest/DeliveryTypeControllerTest.java
- Added and passed 4 tests `DeliveryTypeControllerTest`
- Added `DeliveryTypeHelper`
- Updated `DeliveryTypeController`
=>  OP-196 | Adding Delivery Type Controller Test

src/main/java/org/isf/distype/rest/DiseaseTypeController.java, src/test/java/org/isf/distype/data/DiseaseTypeHelper.java, src/test/java/org/isf/distype/rest/DiseaseTypeControllerTest.java
- Added and passed 4 tests `DiseaseTypeControllerTest`
- Added `DiseaseTypeHelper`
- Updated `DiseaseTypeController`
=> OP-196 | Adding Disease Type Controller Test

.ide-settings/eclipse/OpenHospital-Java-CodeStyle-Formatter.xml, .ide-settings/eclipse/OpenHospital.importorder, .ide-settings/idea/OpenHospital-code-style-configuration.xml, README.md
Add common IDE code style and import definitions and update `README.md` with installation instructions.
=> Add IDE settings and update README.md

src/main/java/org/isf/vaccine/rest/VaccineController.java
Removing `RequestBody` parameter from `@DeleteMapping deleteVaccine` 
Fix OP-241
=> [OP-241] Update Delete VaccineController

.github/workflows/maven.yml, src/main/java/org/isf/patient/rest/PatientController.java
R getPatient(name) -> getPatientByName(name) (deprecated)
R getPatient(code) -> getpatientById(code)
R isPatientPresent(name) -> isNamePresent(name) (manager)
R isPatientPresent(name) -> isPatientPresentByName(name) (service)
=> Some refactoring and deprecations

src/main/java/org/isf/vactype/rest/VaccineTypeController.java
=> OP-259 | Replace @RequestBody with @PathVariable in @DeleteMapping VaccineTypeController

src/main/java/org/isf/ward/rest/WardController.java
=> OP-260 | Replace @RequestBody with  @PathVariable in @DeleteMapping WardController

src/main/java/org/isf/vactype/rest/VaccineTypeController.java, src/test/java/org/isf/vactype/data/VaccineTypeHelper.java, src/test/java/org/isf/vactype/rest/VaccineTypeControllerTest.java
This PR depends of (CORE) https://github.com/informatici/openhospital-core/pull/209
=> OP-201 | Adding VaccineTypeController Testing 

src/main/java/org/isf/visits/rest/VisitsController.java, src/test/java/org/isf/visits/data/VisitHelper.java, src/test/java/org/isf/visits/rest/VisitsControllerTest.java
This depends on https://github.com/informatici/openhospital-core/pull/213
=>  OP-201 | Adding Visit Controller Testing

src/main/java/org/isf/ward/rest/WardController.java
=> OP-275 | Replace @RequestBody with @PathVariable in @GetMapping getCurrentOccupation at WardController 

pom.xml
=> OP-294 | Fixing Testing Compilation Issue related to Checks Failing for PR#68 (API)

src/test/java/org/isf/patient/rest/PatientControllerTest.java
=> Fixing PatientController Tests Failing in PR#68

src/main/java/org/isf/ward/rest/WardController.java, src/test/java/org/isf/admtype/rest/AdmissionTypeControllerTest.java
Found with SpotBugs
Remove creation of `admissionType` as it is not used in the test method.
=> Chore Remove dead store

.gitignore, src/main/java/org/isf/accounting/rest/BillController.java, src/main/java/org/isf/admission/rest/AdmissionController.java, src/main/java/org/isf/admtype/rest/AdmissionTypeController.java, src/main/java/org/isf/disctype/rest/DischargeTypeController.java, src/main/java/org/isf/disease/rest/DiseaseController.java, src/main/java/org/isf/dlvrrestype/rest/DeliveryResultTypeController.java, src/main/java/org/isf/dlvrtype/rest/DeliveryTypeController.java, src/main/java/org/isf/medtype/rest/MedicalTypeController.java, src/main/java/org/isf/opd/rest/OpdController.java, src/main/java/org/isf/operation/rest/OperationController.java, src/main/java/org/isf/opetype/rest/OperationTypeController.java, src/main/java/org/isf/patient/rest/PatientController.java, src/main/java/org/isf/patvac/rest/PatVacController.java, src/main/java/org/isf/pregtreattype/rest/PregnantTreatmentTypeController.java, src/main/java/org/isf/priceslist/rest/PriceListController.java, src/main/java/org/isf/pricesothers/rest/PricesOthersController.java, src/main/java/org/isf/vaccine/rest/VaccineController.java, src/main/java/org/isf/vactype/rest/VaccineTypeController.java, src/main/java/org/isf/visits/rest/VisitsController.java, src/main/java/org/isf/ward/rest/WardController.java
Found with SonarLint which notes
````
Using Collection.size() to test for emptiness works, but using Collection.isEmpty() makes the code more
readable and can be more performant. The time complexity of any isEmpty() method implementation 
should be O(1) whereas some implementations of size() can be O(n).
````
Project had 57 occurrences of `isEmpty()` and 64 occurrences of `size() == 0` before the changes made in this PR.
Also added `logs` directory to .gitignore to simplify future comparisons.
=> Chore Replace "size() == 0" with "isEmpty()"

src/main/java/org/isf/accounting/rest/BillController.java, src/main/java/org/isf/agetype/rest/AgeTypeController.java, src/main/java/org/isf/config/SpringFoxConfig.java, src/main/java/org/isf/disease/rest/DiseaseController.java, src/main/java/org/isf/distype/rest/DiseaseTypeController.java, src/main/java/org/isf/exam/rest/ExamController.java, src/main/java/org/isf/exam/rest/ExamRowController.java, src/main/java/org/isf/examination/rest/ExaminationController.java, src/main/java/org/isf/exatype/rest/ExamTypeController.java, src/main/java/org/isf/hospital/rest/HospitalController.java, src/main/java/org/isf/lab/rest/LaboratoryController.java, src/main/java/org/isf/patient/rest/PatientController.java, src/main/java/org/isf/sms/rest/SmsController.java, src/main/java/org/isf/stats/rest/ReportsController.java, src/main/java/org/isf/supplier/rest/SupplierController.java, src/main/java/org/isf/therapy/rest/TherapyController.java, src/main/java/org/isf/vaccine/rest/VaccineController.java, src/main/java/org/isf/vactype/rest/VaccineTypeController.java, src/main/java/org/isf/visits/rest/VisitsController.java, src/main/java/org/isf/ward/rest/WardController.java
https://openhospital.atlassian.net/browse/OP-378
=> OP-378 Moved springfox auth settings from controllers to centralized config

pom.xml, src/main/java/org/isf/disease/rest/DiseaseController.java, src/main/java/org/isf/vaccine/rest/VaccineController.java, src/test/java/org/isf/disease/rest/DiseaseControllerTest.java, src/test/java/org/isf/vaccine/rest/VaccineControllerTest.java
=> OP-408 Fixing "The data has been updated by someone else”

src/main/java/org/isf/security/LoginApi.java, src/test/java/org/isf/agetype/rest/AgeTypeControllerTest.java, src/test/java/org/isf/disease/rest/DiseaseControllerTest.java, src/test/java/org/isf/distype/rest/DiseaseTypeControllerTest.java, src/test/java/org/isf/dlvrrestype/rest/DeliveryResultTypeControllerTest.java, src/test/java/org/isf/dlvrtype/rest/DeliveryTypeControllerTest.java, src/test/java/org/isf/vaccine/rest/VaccineControllerTest.java, src/test/java/org/isf/vactype/rest/VaccineTypeControllerTest.java, src/test/java/org/isf/visits/rest/VisitsControllerTest.java, src/test/java/org/isf/ward/rest/WardControllerTest.java
Found using IntelliJ's Analyze plugin
=> Chore: remove unused imports

src/main/java/org/isf/admission/rest/AdmissionController.java, src/main/java/org/isf/admtype/rest/AdmissionTypeController.java, src/main/java/org/isf/agetype/rest/AgeTypeController.java, src/main/java/org/isf/disctype/rest/DischargeTypeController.java, src/main/java/org/isf/distype/rest/DiseaseTypeController.java, src/main/java/org/isf/dlvrrestype/rest/DeliveryResultTypeController.java, src/main/java/org/isf/dlvrtype/rest/DeliveryTypeController.java, src/main/java/org/isf/medicalstockward/rest/MedicalStockWardController.java, src/main/java/org/isf/medstockmovtype/rest/MedStockMovementTypeController.java, src/main/java/org/isf/medtype/rest/MedicalTypeController.java, src/main/java/org/isf/opd/rest/OpdController.java, src/main/java/org/isf/operation/rest/OperationController.java, src/main/java/org/isf/opetype/rest/OperationTypeController.java, src/main/java/org/isf/pregtreattype/rest/PregnantTreatmentTypeController.java, src/main/java/org/isf/priceslist/rest/PriceListController.java, src/main/java/org/isf/pricesothers/rest/PricesOthersController.java, src/main/java/org/isf/supplier/rest/SupplierController.java, src/test/java/org/isf/admission/rest/AdmissionControllerTest.java, src/test/java/org/isf/patient/rest/PatientControllerTest.java
See OP-464
There are some small spelling changes in this PR too; as I was reviewing the files I noticed them and couldn't help myself; I had to change them.
=> OP-464 use isEmpty()

src/main/java/org/isf/visits/rest/VisitsController.java
There is no need to use a wrapper version of boolean in this method.
=> Chore: only need a primitive type

src/main/java/org/isf/admission/rest/AdmissionController.java, src/main/java/org/isf/admtype/rest/AdmissionTypeController.java, src/main/java/org/isf/disctype/rest/DischargeTypeController.java, src/main/java/org/isf/disease/rest/DiseaseController.java, src/main/java/org/isf/distype/rest/DiseaseTypeController.java, src/main/java/org/isf/dlvrrestype/rest/DeliveryResultTypeController.java, src/main/java/org/isf/dlvrtype/rest/DeliveryTypeController.java, src/main/java/org/isf/exatype/rest/ExamTypeController.java, src/main/java/org/isf/medstockmovtype/rest/MedStockMovementTypeController.java, src/main/java/org/isf/medtype/rest/MedicalTypeController.java, src/main/java/org/isf/operation/rest/OperationController.java, src/main/java/org/isf/opetype/rest/OperationTypeController.java, src/main/java/org/isf/pregtreattype/rest/PregnantTreatmentTypeController.java, src/main/java/org/isf/vaccine/rest/VaccineController.java, src/main/java/org/isf/vactype/rest/VaccineTypeController.java, src/main/java/org/isf/ward/rest/WardController.java, src/test/java/org/isf/admission/rest/AdmissionControllerTest.java, src/test/java/org/isf/admtype/rest/AdmissionTypeControllerTest.java, src/test/java/org/isf/disctype/rest/DischargeTypeControllerTest.java, src/test/java/org/isf/disease/rest/DiseaseControllerTest.java, src/test/java/org/isf/distype/rest/DiseaseTypeControllerTest.java, src/test/java/org/isf/dlvrrestype/rest/DeliveryResultTypeControllerTest.java, src/test/java/org/isf/dlvrtype/rest/DeliveryTypeControllerTest.java, src/test/java/org/isf/vaccine/rest/VaccineControllerTest.java, src/test/java/org/isf/vactype/rest/VaccineTypeControllerTest.java, src/test/java/org/isf/ward/rest/WardControllerTest.java
See OP-465
The CI job will fail until the Core [PR](https://github.com/informatici/openhospital-core/pull/360) is merged.
=> OP-465 rename codeControl() to isCodePresent()

pom.xml
`com.h2database` dependency defined twice
=> Chore remove dup dependency added Jan 19, 2021

pom.xml, src/main/java/org/isf/config/SecurityConfig.java, src/main/java/org/isf/config/SpringFoxConfig.java, src/main/java/org/isf/security/LoginApi.java, src/main/java/org/isf/security/LoginResponse.java, src/main/java/org/isf/security/OHSimpleUrlAuthenticationSuccessHandler.java, src/main/java/org/isf/security/jwt/JWTConfigurer.java, src/main/java/org/isf/security/jwt/JWTFilter.java, src/main/java/org/isf/security/jwt/TokenProvider.java, src/main/resources/application.properties
The purpose of this PR is to replace the *Basic* Authentication mechanism with the *JWT* Authentication mechanism as a stateless, more secure, cookie independant solution.
**Spring Security**
Fully integrated in Spring Security, main components are:
* a **token provider** that generate the token
* a **login success handler** thet return the generated token on succesfully login
* a **security filter** that check and validate the token
**SpringFox**
* updated spring fox version (that need an update on spring boot and the addition of gson dependency)
* updated *SpringFoxConfig* class to support the JWT security schema and context
=> OP-377 Implements JWT authentication

src/main/java/org/isf/accounting/rest/BillController.java, src/test/java/org/isf/admission/rest/AdmissionControllerTest.java, src/test/java/org/isf/disctype/rest/DischargeTypeControllerTest.java
Remove dead stores (unneeded allocations and/or unused variable).
Found with SpotBugs.
=> Chore: remove dead store

.mvn/wrapper/maven-wrapper.properties
=> OP-629 update maven wrapper version

src/main/java/org/isf/accounting/rest/BillController.java, src/main/java/org/isf/patient/rest/PatientController.java, src/main/java/org/isf/therapy/rest/TherapyController.java, src/main/java/org/isf/vaccine/rest/VaccineController.java, src/main/java/org/isf/vactype/rest/VaccineTypeController.java, src/main/java/org/isf/visits/rest/VisitsController.java, src/main/java/org/isf/ward/rest/WardController.java
=> OP-655 Use interface instead of concreate class

src/main/java/org/isf/patient/rest/PatientController.java, src/main/java/org/isf/therapy/rest/TherapyController.java
See OP-468
Additional files need update since last run of updating
=> OP-468 update license headers

pom.xml, src/main/java/org/isf/lab/rest/LaboratoryController.java
Fix after merge https://github.com/informatici/openhospital-core/pull/623
=> Fix after release

pom.xml
This allows for testing all the updates together.
I will update the individual PRs when this is merged.
=> Chore: update all recent dependabot jar updates

.github/workflows/maven.yml, pom.xml
=> OP-854 Move to JDK 11 - api

pom.xml
Ran `mvn clean test` without issue
Will rebase the dependabot PR once this is merged.
=> Chore: combine all jar updates from dependabot to test and match CORE and GUI

pom.xml
Tests are clean and I will request rebasing of individual PRs when this is committed.
=> Chore: combine all jar updates from dependabot to test and match Core and GUI repos

pom.xml, src/main/java/org/isf/lab/dto/LaboratoryDTO.java, src/main/java/org/isf/lab/rest/LaboratoryController.java, src/main/java/org/isf/patient/dto/PatientDTO.java, src/main/java/org/isf/patient/mapper/PatientMapper.java
See OH2-163.
change the properties father_name and mother_name to fatherName and motherName in the PatientDTO
this is paired with https://github.com/informatici/openhospital-core/pull/861.
=> staging3test addendum

.gitignore, pom.xml, src/main/java/org/isf/opd/dto/OpdWithOperatioRowDTO.java, src/main/java/org/isf/opd/rest/OpdController.java, src/main/java/org/isf/operation/rest/OperationController.java, src/test/java/org/isf/opd/rest/OpdControllerTest.java
See OH2-172.
Paired with https://github.com/informatici/openhospital-core/pull/884.
=> OH2-172 add apis to enhance opd manipulation with operations rows as it is done for oh 1 11

src/main/java/org/isf/malnutrition/rest/MalnutritionController.java, src/test/java/org/isf/disctype/data/DischargeTypeHelper.java, src/test/java/org/isf/vaccine/data/VaccineHelper.java, src/test/java/org/isf/vactype/data/VaccineTypeHelper.java
=> OP-1052: Use String.valueOf() instead of empty string concatenation

src/main/java/org/isf/admission/rest/AdmissionController.java, src/main/java/org/isf/patient/rest/PatientController.java
See OHCS-92.
Paired with https://github.com/informatici/openhospital-core/pull/913.
=> OHCS-92 fix admissions enpoint

src/test/java/org/isf/admission/rest/AdmissionControllerTest.java
Fix: remove no longer existing endpoint after OHSC-92
=> Fix: remove no longer existing endpoint after OHSC-92

Makefile, README.md, docker-compose.yml, src/main/java/org/isf/config/SpringFoxConfig.java
See OP-1060.
Following https://www.baeldung.com/spring-boot-swagger-jwt.
I don't know why, in respect Baeldung indications, we have to add "Bearer " in front of the JWT token in order to make it work
=> OP-1060 Fix Swagger Authentication

src/main/java/org/isf/accounting/rest/BillController.java, src/main/java/org/isf/admission/rest/AdmissionController.java, src/main/java/org/isf/admtype/rest/AdmissionTypeController.java, src/main/java/org/isf/agetype/rest/AgeTypeController.java, src/main/java/org/isf/disctype/rest/DischargeTypeController.java, src/main/java/org/isf/disease/rest/DiseaseController.java, src/main/java/org/isf/distype/rest/DiseaseTypeController.java, src/main/java/org/isf/dlvrrestype/rest/DeliveryResultTypeController.java, src/main/java/org/isf/dlvrtype/rest/DeliveryTypeController.java
See OP-1066
Changes for packages starting with 'A' and 'D'
=> OP-1066 Use new shorthand OHExceptionMessage() constructor for packages A and D

src/main/java/org/isf/exam/rest/ExamController.java, src/main/java/org/isf/exam/rest/ExamRowController.java, src/main/java/org/isf/examination/rest/ExaminationController.java, src/main/java/org/isf/exatype/rest/ExamTypeController.java, src/main/java/org/isf/hospital/rest/HospitalController.java, src/main/java/org/isf/lab/rest/LaboratoryController.java
Changes for packages starting with 'E' , 'H', and 'L'
=> OP-1066 Use new shorthand OHExceptionMessage() constructor for packages E, H, and L

src/main/java/org/isf/malnutrition/rest/MalnutritionController.java, src/main/java/org/isf/medical/rest/MedicalController.java, src/main/java/org/isf/medicalstock/rest/StockMovementController.java, src/main/java/org/isf/medicalstockward/rest/MedicalStockWardController.java, src/main/java/org/isf/medstockmovtype/rest/MedStockMovementTypeController.java, src/main/java/org/isf/medtype/rest/MedicalTypeController.java, src/main/java/org/isf/menu/rest/UserController.java
Changes for package starting with 'M'
=> OP-1066 Use new shorthand OHExceptionMessage() constructor for package M

src/main/java/org/isf/opd/rest/OpdController.java, src/main/java/org/isf/operation/rest/OperationController.java, src/main/java/org/isf/opetype/rest/OperationTypeController.java
Changes for package starting with 'O'
=> OP-1066 Use new shorthand OHExceptionMessage() constructor for package O

src/main/java/org/isf/patient/rest/PatientController.java, src/main/java/org/isf/patvac/rest/PatVacController.java, src/main/java/org/isf/permissions/rest/PermissionController.java, src/main/java/org/isf/pregtreattype/rest/PregnantTreatmentTypeController.java, src/main/java/org/isf/priceslist/rest/PriceListController.java, src/main/java/org/isf/pricesothers/rest/PricesOthersController.java, src/test/java/org/isf/patient/rest/PatientControllerTest.java
Changes for package starting with 'P'
=> OP-1066 Use new shorthand OHExceptionMessage() constructor for package P

src/main/java/org/isf/sms/rest/SmsController.java, src/main/java/org/isf/stats/rest/ReportsController.java, src/main/java/org/isf/supplier/rest/SupplierController.java, src/main/java/org/isf/therapy/rest/TherapyController.java
Changes for package starting with 'S' and 'T'
=> OP-1066 Use new shorthand OHExceptionMessage() constructor for packages S and T

src/main/java/org/isf/vaccine/rest/VaccineController.java, src/main/java/org/isf/vactype/rest/VaccineTypeController.java, src/main/java/org/isf/visits/rest/VisitsController.java, src/main/java/org/isf/ward/rest/WardController.java
Changes for package starting with 'W' and 'W'
=> OP-1066 Use new shorthand OHExceptionMessage() constructor for packages V and W

src/main/java/org/isf/lab/rest/LaboratoryController.java
See OP-1064.
Paired with https://github.com/informatici/openhospital-core/pull/946.
=> OP-1064 Make list of exams laboratory parametric and pageable

src/main/java/org/isf/admission/rest/AdmissionController.java, src/main/java/org/isf/lab/rest/LaboratoryController.java, src/main/java/org/isf/opd/rest/OpdController.java, src/test/java/org/isf/patient/rest/PatientControllerTest.java
Cleanup Javadoc issues found by Intellij Analyze function
=> Chore: fix up Javadoc

src/main/java/org/isf/patient/dto/PatientDTO.java
=> OP-1071 fix the get method

src/main/java/org/isf/login/rest/LoginController.java
On an unrelated note, accessing the settings through static variables is kind of ugly and it would look nicer to do it through @Configuration classes. It would make testing easier also, as static values are harder to mock.
=> OP-1067: Change the default hardcoded value of password length for the one specified in the settings

src/main/java/org/isf/login/rest/LoginController.java
=> OP-1077 Remove password length check as password handling is done in Core

src/main/java/org/isf/lab/rest/LaboratoryController.java
See OP-1086
Using new Core jar; rebuilt and reran all tests successfully
Dependent on: https://github.com/informatici/openhospital-core/pull/978
=> OP-1086: removed deprecated methods from org.isf.lab.model.Laboratory

src/main/java/org/isf/accounting/rest/BillController.java, src/test/java/org/isf/accounting/rest/BillControllerTest.java, src/test/java/org/isf/patient/rest/PatientControllerTest.java
See OP-1083
Goes along with https://github.com/informatici/openhospital-core/pull/976
=> OP-1083: changes from removing deprecated method from PatientBrowserManager

src/main/java/org/isf/lab/dto/LaboratoryDTO.java, src/main/java/org/isf/lab/rest/LaboratoryController.java
=> OH2-199: Fix laboratory api returning null for labDate and registrationDate

src/main/java/org/isf/login/rest/LoginController.java
=> OP-1100 Fix API current user variable in MDC

src/main/java/org/isf/admission/rest/AdmissionController.java, src/main/java/org/isf/examination/rest/ExaminationController.java, src/main/java/org/isf/lab/rest/LaboratoryController.java, src/main/java/org/isf/patient/rest/PatientController.java, src/main/java/org/isf/shared/GenericMapper.java, src/main/java/org/isf/shared/Mapper.java, src/main/java/org/isf/shared/pagination/PageInfoDTO.java, src/main/java/org/isf/shared/pagination/PagedResponseDTO.java, src/test/java/org/isf/patient/data/PatientHelper.java, src/test/java/org/isf/patient/rest/PatientControllerTest.java
=> OH2-189:  Add page info to paginated API

src/main/java/org/isf/lab/rest/LaboratoryController.java
OH2-201.
Paired with https://github.com/informatici/openhospital-core/pull/1006
=> OH2-201: Add the request exam cancellation feature invalid state

rsc/application.properties.dist, src/main/java/org/isf/OpenHospitalApiApplication.java
=> OP-1113 Create PID file for controlling API from scripts

pom.xml
Align project with changes in Core and GUI
Release notes; https://github.com/informatici/openhospital-gui/pull/1786
=> Chore: upgrade to Spring Boot 2.7.13

src/main/java/org/isf/visits/dto/VisitDTO.java
=> Chore: remove unused import

src/main/java/org/isf/admtype/rest/AdmissionTypeController.java, src/main/java/org/isf/dlvrrestype/rest/DeliveryResultTypeController.java, src/main/java/org/isf/dlvrtype/rest/DeliveryTypeController.java, src/main/java/org/isf/examination/rest/ExaminationController.java, src/main/java/org/isf/medtype/rest/MedicalTypeController.java, src/main/java/org/isf/opd/dto/OpdWithOperationRowDTO.java, src/main/java/org/isf/opd/rest/OpdController.java, src/main/java/org/isf/opetype/rest/OperationTypeController.java, src/main/java/org/isf/pregtreattype/rest/PregnantTreatmentTypeController.java, src/main/java/org/isf/priceslist/rest/PriceListController.java, src/main/java/org/isf/pricesothers/rest/PricesOthersController.java, src/test/java/org/isf/admission/rest/AdmissionControllerTest.java
Ran `mvn clean test` successfully
=> Chore: spelling corrections

src/main/java/org/isf/lab/rest/LaboratoryController.java
=> OH2-225: API /laboratories/exams: did not display the data well

src/main/java/org/isf/opd/dto/OpdDTO.java, src/main/java/org/isf/opd/mapper/OpdMapper.java, src/main/java/org/isf/opd/rest/OpdController.java, src/main/java/org/isf/ward/dto/WardDTO.java
=> OH2-226: add param wardCode on api opd search

src/main/java/org/isf/patient/dto/PatientDTO.java
Clean rebuild and all the tests run after the change
=> Chore: set method should return void

src/main/java/org/isf/opd/dto/OpdDTO.java
Ran `mvn clean test` without error after removing the variable and the associated methods.
=> Chore: remove deprecated variable and associated methods

src/main/java/org/isf/opd/rest/OpdController.java, src/main/java/org/isf/patient/rest/PatientController.java
Changing these 3 occurrences of `size() > 0` matches the other 153 occurrences in the project
=> Chore: use isEmpty() instead of testing for size of the collection

src/main/java/org/isf/opd/rest/OpdController.java
See OH2-227.
Paired with https://github.com/informatici/openhospital-core/pull/1059.
=> OH2-227: Persist the opd ward that comes from the front end

src/main/java/org/isf/opd/rest/OpdController.java
=> Chore: compare strings with `equals()` and not `==`

.gitignore, Dockerfile.backend, README.md
=> [OP-1121] and [OP-1122] MRs (Fix for docker file and .env into .gitignore)

src/main/java/org/isf/opd/rest/OpdController.java
Jira Issue [OP-1120](https://openhospital.atlassian.net/browse/OP-1120)
[OP-1120]: https://openhospital.atlassian.net/browse/OP-1120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [OP-1120] Fixed Disease Type Code

pom.xml
Release Notes: https://github.com/spring-projects/spring-boot/releases/tag/v2.7.15
Matches similar update in Core and GUI
=> Upgrade to Spring Boot 2.7.15

src/main/java/org/isf/accounting/rest/BillController.java, src/test/java/org/isf/accounting/rest/BillControllerTest.java
See OP-1130
This is for the accounting package and is matched with the CORE PR: https://github.com/informatici/openhospital-core/pull/1102
=> OP-1130 improve JPA methods

src/main/java/org/isf/admission/rest/AdmissionController.java, src/test/java/org/isf/admission/rest/AdmissionControllerTest.java
See OP-1130
Changes for the admission package
Corresponds the CORE repo changes in https://github.com/informatici/openhospital-core/pull/1104
=> OP-1130 improve JPA methods - admission package

src/main/java/org/isf/agetype/rest/AgeTypeController.java, src/test/java/org/isf/agetype/rest/AgeTypeControllerTest.java
See OP-1130
Changes for the agetype package.
Matches changes in the CORE PR https://github.com/informatici/openhospital-core/pull/1106
=> OP-1130 improve JPA methods - agetype package

src/main/java/org/isf/opd/rest/OpdController.java
=> OH2-239 | 500 error when paged is true on api opd search

src/main/java/org/isf/disctype/rest/DischargeTypeController.java, src/test/java/org/isf/disctype/rest/DischargeTypeControllerTest.java
See OP-1130
Changes for disctype package
Matching CORE PR is https://github.com/informatici/openhospital-core/pull/1115
=> OP-1130 improve JPA methods - disctype package

src/main/java/org/isf/distype/rest/DiseaseTypeController.java, src/test/java/org/isf/distype/rest/DiseaseTypeControllerTest.java
See OP-1130
Changes for distype package
Matches CORE PR https://github.com/informatici/openhospital-core/pull/1116
=> OP-1130 improve JPA methods - distype package

src/main/java/org/isf/dlvrrestype/rest/DeliveryResultTypeController.java, src/test/java/org/isf/dlvrrestype/rest/DeliveryResultTypeControllerTest.java
See OP-1130
Matches changes in CORE PR: https://github.com/informatici/openhospital-core/pull/1117
=> OP-1130 improve JPA methods - dlvrrestype package

src/main/java/org/isf/dlvrtype/rest/DeliveryTypeController.java, src/test/java/org/isf/dlvrtype/rest/DeliveryTypeControllerTest.java
See OP-1130
Changes for dlvrtype package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1118
=> OP-1130 improve JPA methods - dlvrtype package

src/main/java/org/isf/exatype/rest/ExamTypeController.java
See OP-1130
Changes for exatype package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1119
=> OP-1130 improve JPA methods - exatype package

src/main/java/org/isf/disease/rest/DiseaseController.java, src/test/java/org/isf/disease/rest/DiseaseControllerTest.java
See OP-1130
Changes for disease package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1121
=> OP-1130 improve JPA methods - disease package

src/main/java/org/isf/examination/rest/ExaminationController.java
See OP-1130
Changes for examination package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1123
Changes are primarily for code improvement
=> OP-1130 improve JPA methods - examination package

src/main/java/org/isf/lab/rest/LaboratoryController.java
See OP-1130
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1128
=> OP-1130 improve JPA methods - lab package

src/main/java/org/isf/malnutrition/rest/MalnutritionController.java
See OP-1130
Changes for the malnutrition package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1130
=> OP-1130 improve JPA methods - malnutrition package

src/main/java/org/isf/medtype/rest/MedicalTypeController.java
See OP-1130
Changes for `medtype` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1138
=> OP-1130 improve JPA methods - medtype package

src/main/java/org/isf/opd/rest/OpdController.java
See OP-1130
Changes for `opd` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1139
=> OP-1130 improve JPA methods - opd package

src/main/java/org/isf/opetype/rest/OperationTypeController.java
See OP-1130.
Changes for `opetype` package.
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1142
=> OP-1130 improve JPA methods - opetype package

src/main/java/org/isf/pregtreattype/rest/PregnantTreatmentTypeController.java
See OP-1130
Changes for `pregtreattype` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1143
=> OP-1130 improve JPA methods - pregtreattype package

src/main/java/org/isf/vactype/rest/VaccineTypeController.java
See OP-1130
Changes for `vactype` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1144
=> OP-1130 improve JPA methods - vactype package

src/main/java/org/isf/vaccine/rest/VaccineController.java, src/test/java/org/isf/vaccine/rest/VaccineControllerTest.java
See OP-1130
Changes for `vaccine` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1145
=> OP-1130 improve JPA methods - vaccine package

src/main/java/org/isf/ward/rest/WardController.java, src/test/java/org/isf/ward/rest/WardControllerTest.java
See OP-1130
Changes for `ward` package
Matches changes in the CORE PR https://github.com/informatici/openhospital-core/pull/1146
=> OP-1130 improve JPA methods - ward package

src/main/java/org/isf/examination/rest/ExaminationController.java
=> OH2-241 Fix height and weight when null (BAD REQUEST)

src/main/java/org/isf/therapy/rest/TherapyController.java
See OP-1130
Changes for the `therapy` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1148
=> OP-1130 improve JPA methods - therapy package

src/main/java/org/isf/supplier/rest/SupplierController.java
See OP-1130
Changes for the `supplier` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1154
=> OP-1130 improve JPA methods - supplier package

src/main/java/org/isf/pricesothers/rest/PricesOthersController.java
See OP-1130
Changes for `pricesothers` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1155
=> OP-1130 improve JPA methods - pricesothers package

src/main/java/org/isf/patvac/rest/PatVacController.java
See OP-1130
Changes for `patvac` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1157
=> OP-1130 improve JPA methods - patvac package

src/main/java/org/isf/patconsensus/rest/PatientConsensusController.java
See OP-1130
Changes for `patconsensus` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1158
=> OP-1130 improve JPA methods - patconsensus package

src/main/java/org/isf/patient/rest/PatientController.java, src/test/java/org/isf/patient/rest/PatientControllerTest.java
See OP-1130
Changes for the `patient` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1159
=> OP-1130 improve JPA methods - patient package

src/main/java/org/isf/operation/rest/OperationController.java
See OP-1130
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1172
=> OP-1130 improve JPA methods - operation package

src/main/java/org/isf/priceslist/rest/PriceListController.java
See OP-1130
Changes for `priceslist` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1174
=> OP-1130 improve JPA methods - priceslist package

src/main/java/org/isf/menu/rest/UserController.java
See OH2-254.
Also fixed other logic.
=> OH2-254 Fix password and user update

src/main/java/org/isf/menu/rest/UserController.java
See OP-1130
Changes for `menu` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1178
=> OP-1130 improve JPA methods - menu package

src/main/java/org/isf/medstockmovtype/rest/MedStockMovementTypeController.java
See OP-1130
Changes in `medstockmovtype` package
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1182
=> OP-1130 improve JPA methods - medstockmovtype package

src/main/java/org/isf/menu/rest/UserController.java
=> OH2-193 Fix responseCode when userSetting not found

src/main/java/org/isf/medicalstock/rest/StockMovementController.java
See OP-1130
Changes for `medicalstock` package.
Matches changes in CORE PR https://github.com/informatici/openhospital-core/pull/1189
=> OP-1130 improve JPA methods - medicalstock package

src/main/java/org/isf/lab/rest/LaboratoryController.java
=> OH2-258 | Change the value of enum LaboratoryStatus in lowercase

openapi/oh.yaml, src/main/java/org/isf/shared/GenericMapper.java, src/main/java/org/isf/visits/rest/VisitsController.java, src/test/java/org/isf/lab/data/LaboratoryHelper.java, src/test/java/org/isf/lab/data/LaboratoryRowHelper.java, src/test/java/org/isf/lab/rest/LaboratoryControllerTest.java, src/test/java/org/isf/opd/data/OpdHelper.java, src/test/java/org/isf/operation/data/OperationHelper.java, src/test/java/org/isf/vactype/rest/VaccineTypeControllerTest.java, src/test/java/org/isf/visits/rest/VisitsControllerTest.java
Changes for #411 
Modify duplicate @PostMapping in VisitsController
Update oh.yaml
Fix Tests
=> Update PR #411

src/main/java/org/isf/lab/rest/LaboratoryController.java
=> OH2-259 | Fix error message on Laboratory page

README.md, src/main/java/org/isf/config/OpenAPIConfiguration.java
=> Fix: update README.md with screenshots

.github/workflows/maven.yml
Change it to better match the version in GUI
=> Chore: fix maven.yml for JDK 17
